desc "Gerar HTMLs dos guias em pt-BR, use a opcao ONLY='migrations i18n.txt' para criar um unico guia."
task :guias do
  require 'mizuho/generator'

  source = "source/pt-BR"
  html   = "html/pt-BR"
  FileUtils.rm_r(html) if File.directory?(html)
  FileUtils.mkdir_p(html)

  template = File.expand_path("source/templates/guides.html.erb")
  asciidoc_conf = 'asciidoc.conf'

  ignore = ['..', 'icons', 'images', 'templates', 'stylesheets']
  #ignore << 'active_record_basics.txt'
  #ignore << '.gitignore'

  indexless = ['index.txt', 'authors.txt','translators.txt']
  
  # Traverse all entries in source/pt-BR or only those specified in ONLY env variable
  entries = Dir.entries(source)
  if ENV['ONLY']
    only = ENV['ONLY'].split(' ')
    unless only.empty?
      entries = entries.select do |e|
        only.include?(e) || only.include?(e.sub(/\.txt$/, ''))
      end
    end
  end  

  # Traverse all entries in source/
  entries.each do |entry|
    next if ignore.include?(entry) or entry =~ /^\./ # because Vim is always saving hidden swap files

    if File.directory?(File.join(source, entry))
      # If the current entry is a directory, then we will want to compile
      # the 'index.txt' file inside this directory.
      if entry == '.'
        input  = File.join(source, 'index.txt')
        output = File.join(html, "index.html")
      else
        input  = File.join(source, entry, 'index.txt')
        output = File.join(html, "#{entry}.html")
      end
    else
      # If the current entry is a file, then we will want to compile this file.
      input  = File.join(source, entry)
      output = File.join(html, entry).sub(/\.txt$/, '.html')
    end

    begin
      puts "GERANDO => #{output}"
      ENV['MANUALSONRAILS_TOC'] = 'no' if indexless.include?(entry)
      Mizuho::Generator.new(input, :output => output, :template => template, :conf_file => asciidoc_conf).start
    rescue Mizuho::GenerationError
      STDERR.puts "*** ERRO"
      exit 2
    ensure
      ENV.delete('MANUALSONRAILS_TOC')
    end
  end

  # Copy images and css files to html directory. These dirs are in .gitigore and shouldn't be source controlled.
  FileUtils.cp_r File.join(source, '..', 'images'), File.join(html, 'images')
  FileUtils.cp_r File.join(source, '..', 'stylesheets'), File.join(html, 'stylesheets')
end